---
booktitle: Proceedings of the 19th Machine Learning in Computational Biology meeting
conference_number: '19'
shortname: MLCB
start: &1 2024-09-05
end: 2024-09-06
published: 2024-11-17
year: '2024'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLCB2024
month: 0
cycles: false
bibtex_editor: Knowles, David A and Mostafavi, Sara
editor:
- given: David A
  family: Knowles
- given: Sara
  family: Mostafavi
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 19th Machine Learning in Computational Biology meeting
    Held in Seattle, WA, USA on 05-06 September 2024

  Published as Volume 261 by the Proceedings of Machine Learning Research on 17 November 2024.

  Volume Edited by:
    David A Knowles
    Sara Mostafavi

  Series Editors:
    Neil D. Lawrence
date_str: 05--06 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v261"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v261
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v261
volume: '261'
email: ''
conference:
  name: Machine Learning in Computational Biology
  url: https://mlcb.github.io/
  location: Seattle, WA, USA
  dates:
  - *1
  - 2024-09-06
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v261/mlcb2024.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v261/mlcb2024.bib
